name: Dummy Status Check

on:
  pull_request:
    branches: [main]   # pre-merge only

jobs:
  always-pass:
    name: always-pass  # keep this stable
    runs-on: ubuntu-latest
    steps:
      - run: echo ok

